version: '2'

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - themoviedb_network

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "4439:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - themoviedb_network

  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "33069:3306"
    environment:
      MYSQL_DATABASE: themoviedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - themoviedb_network

  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PHP_UPLOAD_MAX_FILESIZE=100MB
    networks:
      - themoviedb_network

#Networks
networks:
  themoviedb_network:
